### ISSUE TITLE
link or file is not accessible

### ISSUE THREAD

**Issue by Michelle-Mings** [gunturbudi/ner-privacy-engineering#1]
Hi, the link https://s.id/Ta9a in your readme is not publicly accessible.

**Comment by gunturbudi** [comment]
Hello, thank you for pointing this out. I have updated the link in the readme file. Here's the link to the model: [https://s.id/1vlLA](https://s.id/1vlLA)

**Comment by Michelle-Mings** [comment]
Thanks, the file is accessible to me now!
